
package Gui;
import javax.swing.JOptionPane;
import Logica.Lista;
import Logica.Nodo;
import Logica.Propietario;
import Logica.Vehiculo;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;


public class Ventana extends javax.swing.JFrame {
    public Lista listaCarros;
    public Lista listaMotos;
    public Lista lista;
    public final int CANTIDADMOTOS=8;
    public final int CANTIDADCARROS=5;
    
    public Ventana() {
        this.listaCarros=new Lista();
        this.listaMotos=new Lista();
        lista = new Lista();
        initComponents();
        this.setTitle("Autor: Nicolas Fonseca 2023");
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Vehiculo = new javax.swing.ButtonGroup();
        Vehiculo2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btIngresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cjPlaca = new javax.swing.JTextField();
        cjIdentificacion = new javax.swing.JTextField();
        R_Carro = new javax.swing.JRadioButton();
        R_Moto = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        Btn_Limpiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cjListado = new javax.swing.JTextArea();
        btSalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnSacar = new javax.swing.JButton();
        R_Carro1 = new javax.swing.JRadioButton();
        R_Moto1 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Construído por Giovanni Briceño - Vinni 2023");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 310, 340, 11);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        btIngresar.setText("Ingresar");
        btIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btIngresar);
        btIngresar.setBounds(170, 140, 120, 22);

        jLabel2.setText("Placa:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 60, 100, 20);

        jLabel3.setText("Identificacion:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 90, 100, 20);
        jPanel1.add(cjPlaca);
        cjPlaca.setBounds(140, 60, 150, 22);
        jPanel1.add(cjIdentificacion);
        cjIdentificacion.setBounds(140, 90, 150, 22);

        Vehiculo.add(R_Carro);
        R_Carro.setText("Carro");
        jPanel1.add(R_Carro);
        R_Carro.setBounds(20, 30, 140, 30);

        Vehiculo.add(R_Moto);
        R_Moto.setText("Moto");
        jPanel1.add(R_Moto);
        R_Moto.setBounds(160, 30, 120, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("ENTRADA ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 0, 70, 16);

        Btn_Limpiar.setText("Limpiar");
        Btn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Limpiar);
        Btn_Limpiar.setBounds(20, 140, 110, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 300, 190);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("LISTADO DE PARQUEADERO");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 10, 250, 16);

        cjListado.setColumns(20);
        cjListado.setRows(5);
        jScrollPane1.setViewportView(cjListado);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 30, 290, 210);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(320, 10, 310, 250);

        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btSalir);
        btSalir.setBounds(530, 300, 100, 22);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSacar.setText("Sacar Primero ");
        btnSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarActionPerformed(evt);
            }
        });
        jPanel3.add(btnSacar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        Vehiculo2.add(R_Carro1);
        R_Carro1.setText("Carro");
        R_Carro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_Carro1ActionPerformed(evt);
            }
        });
        jPanel3.add(R_Carro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 60, -1));

        Vehiculo2.add(R_Moto1);
        R_Moto1.setText("Moto");
        R_Moto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_Moto1ActionPerformed(evt);
            }
        });
        jPanel3.add(R_Moto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("SALIDA");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 210, 300, 80);

        setSize(new java.awt.Dimension(684, 343));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarActionPerformed
        sacarVehiculo();
        
    }//GEN-LAST:event_btnSacarActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        // TODO add your handling code here:
        salir();
    }//GEN-LAST:event_btSalirActionPerformed

    private void btIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIngresarActionPerformed
        ingresarVehiculo();
    }//GEN-LAST:event_btIngresarActionPerformed

    private void Btn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LimpiarActionPerformed
        cjPlaca.setText("");
        cjIdentificacion.setText("");
        Vehiculo.clearSelection();
        Vehiculo2.clearSelection();
    }//GEN-LAST:event_Btn_LimpiarActionPerformed

    private void R_Carro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_Carro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R_Carro1ActionPerformed

    private void R_Moto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_Moto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R_Moto1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Limpiar;
    private javax.swing.JRadioButton R_Carro;
    private javax.swing.JRadioButton R_Carro1;
    private javax.swing.JRadioButton R_Moto;
    private javax.swing.JRadioButton R_Moto1;
    private javax.swing.ButtonGroup Vehiculo;
    private javax.swing.ButtonGroup Vehiculo2;
    private javax.swing.JButton btIngresar;
    private javax.swing.JButton btSalir;
    private javax.swing.JButton btnSacar;
    private javax.swing.JTextField cjIdentificacion;
    private javax.swing.JTextArea cjListado;
    private javax.swing.JTextField cjPlaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
        
        
    private void ingresarVehiculo(){
    
     DateFormat hora=new SimpleDateFormat("HH:mm:ss");
     String horaEntrada =hora.format(new Date());
     Vehiculo vehiculo=new Vehiculo(horaEntrada);
     vehiculo.setTipoVehiculo(Vehiculo.getSelection().getActionCommand()); 

     if (R_Carro.isSelected()) {
           vehiculo.setTipoVehiculo("Carro");
      } else if (R_Moto.isSelected()) {
        vehiculo.setTipoVehiculo("Moto");
      }
     vehiculo.setPlaca(cjPlaca.getText());
     vehiculo.setIdentificacion(cjIdentificacion.getText());
     Nodo nodo = new Nodo(vehiculo);
     if(vehiculo.getTipoVehiculo().equals("Moto")){
         if(listaMotos.contarEspacios()< CANTIDADMOTOS){
             listaMotos.adicionarInicio(nodo);
             
         }else{
             JOptionPane.showMessageDialog(this, "No hay cupó para motos en el parqueadero", "Error", JOptionPane.INFORMATION_MESSAGE);
         }
     }else{
         if(listaCarros.contarEspacios()< CANTIDADCARROS){
             listaCarros.adicionarInicio(nodo);
             
         }else{
             JOptionPane.showMessageDialog(this, "No hay cupó para carros en el parqueadero", "Error", JOptionPane.INFORMATION_MESSAGE);
         }
         
     }
     
     this.actualizaListado();
     
     
    }
    private void atender() {
        JOptionPane.showMessageDialog(this, "Atender", "ATENCION", JOptionPane.INFORMATION_MESSAGE);
        
        
        lista.borrarPrimero();
        this.actualizaListado();
    }
    private void actualizaListado(){
        
        this.cjListado.setText(listaMotos.obtenerLista()+listaCarros.obtenerLista());
    }

    private void salir() {
        System.exit(0);
    }
    private void sacarVehiculo(){
        
        String sacar="";
        sacar=Vehiculo2.getSelection().getActionCommand();
        if(R_Carro1.isSelected()){
            sacar="Carro";
        }else if (R_Moto1.isSelected()){
            sacar="Moto";
        }
        
        if (sacar.equals("Moto")){
            if(listaMotos.nodoPrincipal==null){
                JOptionPane.showMessageDialog(this, "No hay motos en el parqueadero", "Error", JOptionPane.INFORMATION_MESSAGE);
            }else{
                listaMotos.borrarPrimero();
            }   
        }else if (sacar.equals("Carro")){
            
            if(listaCarros.nodoPrincipal==null){
                JOptionPane.showMessageDialog(this, "No hay carros en el parqueadero", "Error", JOptionPane.INFORMATION_MESSAGE);
            }else{
                listaCarros.borrarPrimero();
            }  
        }
        this.actualizaListado();
        
    }
    
    
}
